### ISSUE TITLE
The "DBApplication" template looks like missing some files

### ISSUE THREAD

**Issue by Lemonlee8** [Andrey-Bushman/Revit2017AddInTemplateSet#6]
Hi Andrey, when I create a new "Revit 2017 External DBApplication" project，VS show tow dialog like this:
![image](https://cloud.githubusercontent.com/assets/7747035/23305128/4400baea-fad8-11e6-8afa-29f604a9d2db.png)
![image](https://cloud.githubusercontent.com/assets/7747035/23305148/5cb93828-fad8-11e6-82ca-9ca15f503bae.png)

It means the  file named "*.re.chm" is missing. Then, the project created can not work.

thank you...

**Comment by Andrey-Bushman** [comment]
Thank you for your response. I fixed this bug right now. Check it again.

**Comment by Lemonlee8** [comment]
Cool, It's OK,thank you.
